### ISSUE TITLE
Issues with Python 3.12

### ISSUE THREAD

**Issue by julian-belina** [alubbock/microbench#15]
Hello,

when installing microbench with python 3.12 the following error occurs:

`  AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`

An upper limit should be put in the installation proceedure. Also it would be nice to make the library compatible to new python versions if you got spare capacities.

**Comment by alubbock** [comment]
Hi Julian,

Thanks for the report. This issue is fixed in the latest release, v0.9.1. You should now be able to `pip install microbench` using Python 3.12.

Best regards,
Alex
